apps/operation/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from operation.views import UploadView, AboutView, CartView, ApplyDeleteView

urlpatterns = [
	url(r'^upload/$', UploadView.as_view(), name='upload'),
	url(r'^about/$', AboutView.as_view(), name='about'),
	url(r'^cart/$', CartView.as_view(), name='cart'),
	url(r'^apply_delete/$', ApplyDeleteView.as_view(), name='delete'),
]

apps/service/urls.py
from django.conf.urls import url
#from .models import WriteType, Writer, Visa
from service.views import DocView, VisaView, DocDetailView

urlpatterns = [
    url(r'^doc/$', DocView.as_view(), name='doc'),
    url(r'^visa/$', VisaView.as_view(), name='visa'),
    url(r'^doc/detail/(?P<doc_id>\d+)$', DocDetailView.as_view(), name='doc-detail'),
]

apps/university/urls.py
from django.conf.urls import url

from .views import UniversityView, EstimateView, StrategyView, ArticleView, StrategyListView, UniversityDetailView, MajorApplyView, ResultView

urlpatterns = [
    url(r'^university/$', UniversityView.as_view(), name='university'),
    url(r'^university/detail/(?P<university_id>\d+)$', UniversityDetailView.as_view(), name='univer-detail'),
    url(r'^estimate/$', EstimateView.as_view(), name='estimate'),
    url(r'^strategy/$', StrategyView.as_view(), name='strategy'),
    url(r'^strategy-list/$', StrategyListView.as_view(), name='strategy-list'),
    url(r'^strategy/article/(?P<article_id>\d+)$', ArticleView.as_view(), name='article'),
    url(r'^major-apply/$', MajorApplyView.as_view(), name='major-apply'),
	url(r'^estimate-result/$', ResultView.as_view(), name='result'),
]

apps/users/urls.py
from django.conf.urls import url
from users.views import RegisterView, LoginView, LogoutView, IndexView, HighApplyView, UsercenterView, MyApplyView, MyOrderView, MyAskView, MyQstView, CaseView

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^highapply/$', HighApplyView.as_view(), name='highapply'),
    url(r'^usercenter/$', UsercenterView.as_view(), name='usercenter'),
    url(r'^myapply/$', MyApplyView.as_view(), name='myapply'),
    url(r'^myorder/$', MyOrderView.as_view(), name='myorder'),
    url(r'^myask/$', MyAskView.as_view(), name='myask'),
    url(r'^myquestion/$', MyQstView.as_view(), name='myquestion'),
    url(r'^wincase/(?P<case_id>\d+)$', CaseView.as_view(), name='wincase'),
]

xiyou/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
#设置图片显示
from django.views.static import serve
from xiyou.settings import MEDIA_ROOT

import xadmin

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^captche/', include('captcha.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':MEDIA_ROOT}),
	url(r'^ueditor/',include('DjangoUeditor.urls' )),
    url(r'', include('apps.users.urls', namespace='user')),
    url(r'', include('apps.service.urls', namespace='service')),
    url(r'', include('apps.operation.urls', namespace='operation')),
    url(r'', include('apps.university.urls', namespace='university')),
]

apps/operation/models.py
# -*- coding: utf-8 -*-
from django.db import models
from datetime import datetime
from users.models import UserProfile
from university.models import University, Major

# Create your models here.


class UserMajor(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name=u'用户')
    university = models.ForeignKey(University, verbose_name=u'学校')
    major = models.ForeignKey(Major, verbose_name=u'专业')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'申请时间')

    class Meta:
        verbose_name = u'申请专业'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.major


class UserAsk(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name=u'用户')
    problem = models.CharField(max_length=300, verbose_name=u'问题')
    answer = models.CharField(max_length=300, verbose_name=u'回答', null=True, blank=True)
    teacher = models.CharField(verbose_name=u'回答者', max_length=30, null=True, blank=True)
    status = models.IntegerField(choices=((1, u'已解决'),(0, u'未解决')), default=0)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'提问时间')

    class Meta:
        verbose_name = u'用户问题'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.problem


class HighApply(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name=u'用户')
    real_name = models.CharField(verbose_name=u'姓名', max_length=40, null=True)
    country = models.CharField(verbose_name=u'意向国家', max_length=30)
    type = models.CharField(verbose_name=u'意向层次', max_length=30)
    major = models.CharField(verbose_name=u'意向专业', max_length=30)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'申请时间')

    class Meta:
        verbose_name = u'高端申请'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.country


class UserCart(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name=u'用户')
    store_id = models.IntegerField(default=0, verbose_name=u'类型id')
    store_type = models.IntegerField(choices=((1, u'文书'), (2, u'签证')), default=1, verbose_name=u'购物车类型')
    nums = models.IntegerField(verbose_name=u'数量', null=True, blank=True)
    status = models.IntegerField(choices=((1, u'已付款'),(0, u'未付款')), default=0, verbose_name=u'订单状态')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'加入时间')

    class Meta:
        verbose_name = u'购物车'
        verbose_name_plural = verbose_name	

    def __unicode__(self):
        return self.user

apps/university/models.py
# -*- coding: utf-8 -*-
from django.db import models
from datetime import datetime

# Create your models here.


class Country(models.Model):
    name = models.CharField(verbose_name=u'国家名称', max_length=150)
    image = models.ImageField(upload_to=u'university/country/%y/%m', verbose_name=u'logo', max_length=150, null=True)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)

    class Meta:
        verbose_name = u'国家'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class Level(models.Model):
    name = models.CharField(verbose_name=u'学历层次名称', max_length=50)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)\


    class Meta:
        verbose_name = u'学历层次'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class University(models.Model):
    name = models.CharField(verbose_name=u'学校名称', max_length=200)
    image = models.ImageField(verbose_name=u'首页展示图', upload_to=u'university/index', max_length=200)
    logo = models.ImageField(verbose_name=u'校徽', upload_to=u'university/logo', max_length=200, default='university/logo/logo.jpg')
    english_name = models.CharField(verbose_name=u'英文名', max_length=200)
    country = models.ForeignKey(Country, verbose_name=u'所属国家')
    city = models.CharField(verbose_name=u'所属城市', max_length=100)
    type = models.CharField(choices=(('private',u'私立'), ('public', u'公立')), default='public', max_length=13, verbose_name=u'学校类型')
    level = models.ForeignKey(Level, verbose_name=u'学历层次', null=True)
    bulid_time = models.DateTimeField(verbose_name=u'建校时间', null=True, blank=True)
    tea_stu = models.CharField(verbose_name=u'师生比', max_length=10)
    students = models.IntegerField(verbose_name=u'学生人数', default=0)
    tuition = models.IntegerField(verbose_name=u'学费', default=0)
    accept_rate = models.CharField(verbose_name=u'录取率', max_length=30)
    address = models.CharField(verbose_name=u'学校地址', max_length=10)
    end_time = models.DateTimeField(verbose_name=u'截止日期', null=True, blank=True)
    url = models.CharField(verbose_name=u'网址', max_length=200)
    rank = models.IntegerField(verbose_name=u'排名', default=0)
    desc = models.TextField(verbose_name=u'简介', null=True, blank=True)
    college_gpa = models.FloatField(verbose_name=u'本科GPA', default=75.00)
    college_toefl = models.FloatField(verbose_name=u'本科托福', default=110.00)
    college_ielts = models.FloatField(verbose_name=u'本科雅思', default=6.00)
    graduate_gpa = models.FloatField(verbose_name=u'研究生GPA', default=75)
    graduate_toefl = models.FloatField(verbose_name=u'研究生托福', default=110.00)
    graduate_ielts = models.FloatField(verbose_name=u'研究生雅思', default=6.00)
    click_num = models.IntegerField(verbose_name=u'点击数', default=0)
    show_index = models.IntegerField(verbose_name=u'是否首页显示', choices=((1, u'首页显示'),(0, u'首页不显示')), default=0)
    recommend = models.IntegerField(verbose_name=u'是否推荐', choices=((1, u'推荐'),(0, u'不推荐')), default=0)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)

    class Meta:
        verbose_name = u'大学信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def get_all_major(self):
        return self.major_set.all()


class MajorField(models.Model):
    name = models.CharField(verbose_name=u'专业方向名称', max_length=40)
    desc = models.CharField(verbose_name=u'描述', null=True, blank=True, max_length=100)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)

    class Meta:
        verbose_name = u'专业方向'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name		


class Major(models.Model):
    name = models.CharField(verbose_name=u'专业名称', max_length=50)
    english_name = models.CharField(verbose_name=u'英文名称', max_length=100, null=True, blank=True)
    university = models.ForeignKey(University, verbose_name=u'所属大学', null=True, blank=True)
    desc = models.CharField(verbose_name=u'专业描述', null=True, blank=True, max_length=100)
    type = models.CharField(choices=(('college', u'本科'), ('graduate', u'研究生')), default='college', max_length=15, verbose_name=u'学位类型')
    field = models.ForeignKey(MajorField, verbose_name=u'专业方向')
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)

    class Meta:
        verbose_name = u'专业信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class Scenery(models.Model):
    title = models.CharField(verbose_name=u'标题', max_length=50, null=True, blank=True)
    university = models.ForeignKey(University, verbose_name=u'所属大学')
    image = models.ImageField(upload_to=u'university/scenery/%y/%m', verbose_name=u'校园风光',null=True, blank=True, max_length=200)
    add_time = models.DateTimeField(verbose_name=u'添加时间', default=datetime.now)

    class Meta:
        verbose_name = u'校园风光'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.title

apps/university/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.shortcuts import HttpResponse, HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import login, authenticate, logout
from django.core.urlresolvers import reverse
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
import json

from university.models import Country, Level, University, Major, Scenery
from information.models import Article, WinCase
from users.models import BannerOther
from operation.models import UserAsk, UserMajor


# Create your views here.


class UniversityView(View):
    def get(self, request):
        all_country = Country.objects.all()
        all_level = Level.objects.all()
        all_university = University.objects.all()
        banner_list = BannerOther.objects.all()[:3]

        country_id = request.GET.get('country', '')
        type = request.GET.get('type', '')
        level_id = request.GET.get('level', '')

        if country_id:
            all_university = all_university.filter(country=int(country_id))

        if type:
            all_university = all_university.filter(type=type)

        if level_id:
            all_university = all_university.filter(level=int(level_id))

        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_university, 2, request=request)

        universities = p.page(page)

        return render(request, 'university.html', {'all_country': all_country,
                                                   'all_level': all_level,
                                                   'all_university': universities,
                                                   'country_id': country_id,
                                                   'type': type,
                                                   'level_id': level_id,
                                                   'banner_list': banner_list
                                                   })


class UniversityDetailView(View):
    def get(self, request, university_id):
        
        university = University.objects.get(pk=int(university_id))

        university.click_num += 1
        university.save()
		
        all_scenery = Scenery.objects.filter(university=int(university_id))
        view_other_list = University.objects.order_by('-click_num')[:4]
        recommend_list = University.objects.filter(recommend=1)[:6]
        return render(request, 'university-detail.html', {'university': university, 'recommend_list': recommend_list,'view_other_list': view_other_list, 'all_scenery': all_scenery})


class EstimateView(View):
    def get(self, request):
        all_country = Country.objects.all()
        return render(request, 'estimate.html', {'all_country': all_country})


class StrategyView(View):
    def get(self, request):
        all_country = Country.objects.all()
        country_id = request.GET.get('country', '1')
        all_article = Article.objects.all().filter(status=1)
        win_case = WinCase.objects.all()[:6]
        ask_list =  UserAsk.objects.all()[:3]
        commend_list = University.objects.filter(recommend=1)[:6]

        if country_id:
            all_article = all_article.filter(country=int(country_id))	
            art_strategy = 	all_article.filter(category='gl')[:5]
            art_forum = 	all_article.filter(category='lt')[:5]
            art_counsel = 	all_article.filter(category='zx')[:5]			

        return render(request, 'strategy.html', {'all_country': all_country, 'art_strategy': art_strategy, 'art_forum': art_forum, 'art_counsel': art_counsel, 'country_id': country_id, 'win_case': win_case, 'ask_list': ask_list, 'commend_list':commend_list})


class StrategyListView(View):
    def get(self, request):
        type = request.GET.get('type', 'gl')
        all_article = Article.objects.all()

        if type and type != 'al':
            all_article = all_article.filter(category=type)

        if type == 'al':
            all_article = WinCase.objects.all()

        return render(request, 'strategy-list.html', {'all_article': all_article, 'type': type})


class ArticleView(View):
    def get(self, request, article_id):
        article = Article.objects.get(pk=int(article_id))
        return render(request, 'article.html', {'article': article})


class MajorApplyView(View):
    def post(self, request):
        if not request.user.is_authenticated():
            json_data = {'status': 'nologin', 'msg': '您已申请该专业！'}
            return HttpResponse(json.dumps(json_data), content_type="application/json")

        major = UserMajor.objects.filter(user=request.user).filter(major_id=int(request.POST.get('major_id', '')))

        if major:
            json_data = {'status': 'fail', 'msg': '您已申请该专业！'}
            return HttpResponse(json.dumps(json_data), content_type="application/json")

        all_apply_majors = UserMajor.objects.filter(user=request.user)
        if len(all_apply_majors) >= 5:
            json_data = {'status': 'fail', 'msg': '申请的专业不能多于5个！'}
            return HttpResponse(json.dumps(json_data), content_type="application/json")
        else:
            major_id = request.POST.get('major_id', '')
            user_major = UserMajor()
            user_major.user = request.user
            user_major.university = University.objects.get(id=int(Major.objects.get(id=int(major_id)).university_id))
            user_major.major_id = int(major_id)
            user_major.save()
            json_data = {'status': 'success', 'msg': '申请成功'}
            return HttpResponse(json.dumps(json_data), content_type="application/json")
			
	
class ResultView(View):
	def post(self, request):
		return render(request, 'result.html')

templates/footer.html
{% load staticfiles %}
<div class="foot">
	<div class="wrap clearfix">
		<div class="foot-logo fl"> 
			<img width="250px" height="100px" src="{% static 'img/logo-foot.jpg' %}" alt="">
		</div>
		<div class="line fl">
			<img src="{% static 'img/line-foot.png' %}" alt="">
		</div>
		<div class="foot-con fl">
			<p>24小时服务热线：<span>010-88888888</span></p>
			<ul class="fenxiang clearfix">
				<li>好友分享：</li>
				<li><a href=""><img src="{% static 'img/weixin.png' %}" alt=""></a></li>
				<li><a href=""><img src="{% static 'img/weibo.png' %}" alt=""></a></li>
				<li><a href=""><img src="{% static 'img/douban.png' %}" alt=""></a></li>
				<li><a href=""><img src="{% static 'img/renren.png' %}" alt=""></a></li>
			</ul>
		</div>
	</div>
	<div class="about">
		   <ul class="clearfix">
			<li><a href="{% url 'operation:about' %}">关于我们</a></li>
			<li><a href="">友情链接</a></li>
			<li><a href="">意见反馈</a></li>
			<li><a href="">商务合作</a></li>
			<li><a href="">联系我们</a></li>
		  </ul>	
		  <p> Copyright ? 2016 西柚留学网 All rights reserved.</p>
	</div>
</div>

templates/usercenter-base.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/global.css' %}">

	<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
	{% block css %}{% endblock %}
</head>

<body>
	<div class="top-header">
		<div class="wrap clearfix">
			<p class="top-header-l">欢迎来到西柚留学网！咨询热线：<span>010-62514855</span></p>
			<ul class="top-header-r">
				{% if request.user.is_authenticated %}
				<li class="deng">您好，</li>
				 <li class="deng"><a href="{% url 'user:logout' %}">注销</a></li>
				<li id="wo"><a href="{% url 'user:usercenter' %}">|&nbsp{{ request.user.username }}</a></li>
				{% else %}
					<li class="deng">您好，请<a href="{% url 'user:login' %}">登录</a></li>
					<li class="deng">免费<a href="{% url 'user:register' %}">注册</a></li>
				{% endif %}
					<li id="guan"><a href="">|&nbsp关注西柚</a></li>
					<li id="ke"><a href="">|&nbsp客户服务</a></li>
					<li id="dao"><a href="">|&nbsp网站导航</a></li>
			</ul>
			<div id="wode" class="wode">
				<ul>
					<li><a href="{% url 'user:myorder' %}">我的订单</a></li>
					<li><a href="{% url 'user:usercenter' %}">账号管理</a></li>				
					<li><a href="{% url 'user:myask' %}">我的问答</a></li>
				</ul>
			</div>
			<div id="guanzhu" class="guanzhu">
				<img src="{% static 'img/weitu.png' %}" alt="">
			</div>
			<div id="kefu" class="kefu">
				<ul>
					<li><a href="{% url 'operation:about' %}">公司简介</a></li>
					<li><a href="{% url 'operation:about' %}">帮助中心</a></li>
					<li><a href="{% url 'operation:about' %}">联系我们</a></li>
					
				</ul>
			</div>
			<div id="daohang" class="daohang clearfix">
				<ul class="school">
					<li><a href="">美国院校</a></li>
					<li><a href="">英国院校</a></li>
					<li><a href="">加拿大院校</a></li>
					<li><a href="">澳洲院校</a></li>
				</ul>
				<ul class="news">
					<li><a href="">留学资讯</a></li>
					<li><a href="">院校数据</a></li>
					<li><a href="">院校排行</a></li>
				</ul>
				<ul class="server">
					<li><a href="">特色服务</a></li>
					<li><a href="">文书服务</a></li>
					<li><a href="">签证服务</a></li>
					<li><a href="">行程服务</a></li>
				</ul>
			</div>
		</div>
	</div>

	<div class="search">
		<div class="wrap clearfix">
			<div class="logo-top">
				<img src="{% static 'img/logo-top.png' %}" alt="">
			</div>
			<div class="back">
			   <h3>关于西柚</h3>
			   <a href="{% url 'user:index' %}">返回首页</a>
				
			</div>
			<div class="search-box clearfix">
				<input type="text" value="请输入院校名称"><img src="{% static 'img/fangda.png' %}" alt="">
				<button>搜索</button>
			</div>
			<div id="shopping" class="shopping clearfix">
				<img src="{% static 'img/shopping-car.png' %}" alt="">
				<p>我的购物车</p>
				<span>0</span>
				<img class="new" src="{% static 'img/new.png' %}" alt="">
			</div>
			<div id="shopping-down" class="shopping-down">
				<p>最近加入的产品：</p>
				<p class="chan clearfix"><img class="fl" src="{% static 'img/alogo.png' %}" alt=""><a href="">美国威廉玛丽学院留学申请<br>
				￥：<span>36000</span>美元/年
				</a>
				</p>
				<div class="sh-foot">
					<ul class="clearfix">
						<li class="fl">共1件商品</li>
						<li class="fr"><a href="">查看购物车</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
		
<script type="text/javascript">



			var wode = document.getElementById("wode");
			var wo = document.getElementById("wo");		
				wo.onmouseover=function(){
					wode.style.display = "block";
					wo.className="hi"
					wode.onmouseover=function(){
						wo.className="hi"
						this.style.display = "block";
					}
				}
				wo.onmouseout=function() {
					wode.style.display = "none";
					wo.className=""	
					wode.onmouseout=function(){
						this.style.display = "none";
						wo.className=""
					}
			     }

			var guanzhu = document.getElementById("guanzhu");
			var guan = document.getElementById("guan");		
				guan.onmouseover=function(){
					guanzhu.style.display = "block";
					guan.className="hi"
					guanzhu.onmouseover=function(){
						guan.className="hi"
						this.style.display = "block";
					}
				}
				guan.onmouseout=function() {
					guanzhu.style.display = "none";
					guan.className=""	
					guanzhu.onmouseout=function(){
						this.style.display = "none";
						guan.className=""
					}
			     }

			var kefu = document.getElementById("kefu");
			var ke = document.getElementById("ke");		
				ke.onmouseover=function(){
					kefu.style.display = "block";
					ke.className="hi"
					kefu.onmouseover=function(){
						ke.className="hi"
						this.style.display = "block";
					}
				}
				ke.onmouseout=function() {
					kefu.style.display = "none";
					ke.className=""	
					kefu.onmouseout=function(){
						this.style.display = "none";
						ke.className=""
					}
			     }

			var daohang = document.getElementById("daohang");
			var dao = document.getElementById("dao");		
				dao.onmouseover=function(){
					daohang.style.display = "block";
					dao.className="hi"
					daohang.onmouseover=function(){
						dao.className="hi"
						this.style.display = "block";
					}
				}
				dao.onmouseout=function() {
					daohang.style.display = "none";
					dao.className=""	
					daohang.onmouseout=function(){
						this.style.display = "none";
						dao.className=""
					}
			     }



			

			var shopping = document.getElementById("shopping");
			var down = document.getElementById("shopping-down");		
				shopping.onclick=function(ev){
					var oEven=ev||event;
				  down.style.display = "block";
				  oEven.cancelBubble=true;
				
				}
				document.onclick=function(){
					down.style.display = "none";
				}


</script>
    <div class="wrap about clearfix">
    	<div class="fl our">
    		<ul class="about-our">
    		    <li class="pic">
    		      <img src="{% static 'img/touxiang.png' %}" alt="">
    	     	   <a href="wode.html">更换头像</a>
    	     	   <p>欢迎您，1***9</p></li>
    			<li {% if request.path|slice:'5' == '/user' %}class="nn"{% endif %}><a href="{% url 'user:usercenter' %}">账号管理</a></li>
    			<li {% if request.path|slice:'5' == '/myap' %}class="nn"{% endif %}><a href="{% url 'user:myapply' %}">我的申请</a></li>
    			<li {% if request.path|slice:'5' == '/myor' %}class="nn"{% endif %}><a href="{% url 'user:myorder' %}">我的订单</a></li>
    			<li><a href="">上传文书</a></li>
    			<li {% if request.path|slice:'5' == '/myas' %}class="nn"{% endif %}><a href="{% url 'user:myask' %}">我的问答</a></li>
    		</ul>
    	</div>
	{% block content %}{% endblock %}
	</div>
	{% include 'footer.html' %}


	{% block js %}{% endblock %}
</body>
</html>